async function openUsers(){
 showWorkspace('tickets');activeWorkspace='users';$('ticket-workspace').hidden=true;$('validation-workspace').hidden=true;$('users-workspace').hidden=false;$('breadcrumb').textContent='Settings / Users & User Access';
 $('users-content').innerHTML='<p>Loading accounts.</p>';
 try{
  const data=await api('/api/users');
  $('users-content').innerHTML=`<section class="panel" style="padding:24px;margin-bottom:20px"><h2>Create user</h2><p>Only accounts listed here can sign in. New users receive staff access. Use a work email at findme.com.ph.</p><form id="user-create" class="formgrid" style="margin-top:18px"><label class="field">Name<input name="name" required maxlength="120" autocomplete="off"></label><label class="field">Work email<input name="email" type="email" required autocomplete="off"></label><label class="field">Password<input name="password" type="password" required minlength="12" maxlength="256" autocomplete="new-password"></label><div class="actions"><button type="submit" class="primary">Create user</button></div><div class="error full" id="user-error" role="alert"></div></form></section><section class="panel"><div class="panelhead"><h2>Users</h2></div><div class="tablewrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Access</th><th>Actions</th></tr></thead><tbody>${data.users.map((u,i)=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role==='admin'?'Administrator':'Staff'}</td><td>${u.active?'Active':'Disabled'}</td><td><button data-user-password="${i}">Set password</button> <button data-user-toggle="${i}" ${u.email===data.currentUser?'disabled':''}>${u.active?'Disable':'Enable'}</button></td></tr>`).join('')}</tbody></table></div></section><section class="panel" style="padding:24px;margin-top:20px"><h2>Google Sheets import</h2><p>Import a complete workbook snapshot into this website. App edits are preserved and conflicts are flagged. This does not change the source Google Sheet.</p><label class="field" style="margin-top:16px">Workbook snapshot<input id="sheet-snapshot-file" type="file" accept=".json,application/json"></label><button id="upload-sheet-snapshot">Import snapshot</button> <button id="connect-scheduled-import">Connect scheduled refresh</button><p id="import-result" role="status"></p><div id="sync-key-result"></div></section><section class="panel" style="padding:24px;margin-top:20px"><h2>Access history</h2>${data.audit.map(a=>`<p>${esc(a.at)} � ${esc(a.actor)} � ${esc(a.action)} � ${esc(a.email)}</p>`).join('')||'<p>No account changes yet.</p>'}</section>`;
  $('user-create').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('/api/users',{action:'create',...Object.fromEntries(new FormData(f))});f.reset();toast('User created');await openUsers();}catch(err){$('user-error').textContent=err.message;}finally{f.elements.password.value='';b.disabled=false;}};
  document.querySelectorAll('[data-user-toggle]').forEach(b=>b.onclick=async()=>{const u=data.users[+b.dataset.userToggle];b.disabled=true;try{await api('/api/users',{action:u.active?'disable':'enable',email:u.email,version:u.version});await openUsers();}catch(e){toast(e.message);b.disabled=false;}});
  document.querySelectorAll('[data-user-password]').forEach(b=>b.onclick=()=>{
   const u=data.users[+b.dataset.userPassword],d=document.createElement('dialog');d.innerHTML=`<div class="modalhead"><h2>Set password</h2><button type="button" aria-label="Close">x</button></div><form class="modalbody"><p>${esc(u.email)}</p><label class="field">New password<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><p>Existing app sessions will be signed out.</p><div class="error" role="alert"></div><div class="actions"><button type="submit" class="primary">Save password</button></div></form>`;document.body.append(d);d.querySelector('[aria-label="Close"]').onclick=()=>{d.close();d.remove();};d.addEventListener('cancel',()=>d.remove());d.showModal();
   d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,button=f.querySelector('button');button.disabled=true;try{await api('/api/users',{action:'password',email:u.email,version:u.version,password:f.elements.password.value});d.close();d.remove();if(u.email===data.currentUser){location.replace('/');return;}toast('Password updated');await openUsers();}catch(err){d.querySelector('.error').textContent=err.message;}finally{f.elements.password.value='';button.disabled=false;}};
  });
  $('upload-sheet-snapshot').onclick=async()=>{const file=$('sheet-snapshot-file').files[0];if(!file){$('import-result').textContent='Choose a complete snapshot file first.';return;}const b=$('upload-sheet-snapshot');b.disabled=true;$('import-result').textContent='Importing.';try{const result=await api('/api/sheet-import',JSON.parse(await file.text()));$('import-result').textContent=`Import complete: ${result.total.toLocaleString()} tickets, ${result.added} added, ${result.updated} updated, ${result.conflicts} conflicts.`;sheetRevision=null;await pollSheetSync();}catch(e){$('import-result').textContent=e.message;}finally{b.disabled=false;}};
  $('connect-scheduled-import').onclick=async()=>{const b=$('connect-scheduled-import');b.disabled=true;try{const result=await api('/api/sheet-import/key',{});$('sync-key-result').innerHTML='<p>Save this key in the scheduled refresh helper. It allows workbook imports only. Generating another key replaces the previous one.</p><label class="field">Import key (shown once)<input id="scheduled-import-key" readonly type="password"></label>';$('scheduled-import-key').value=result.token;const download=document.createElement('button');download.textContent='Download refresh connection';download.onclick=()=>{const url=URL.createObjectURL(new Blob([result.token],{type:'application/octet-stream'}));const link=document.createElement('a');link.href=url;link.download='cs-desk-import-key.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('sync-key-result').append(download);}catch(e){toast(e.message);}finally{b.disabled=false;}};
 }catch(e){$('users-content').innerHTML='<p class="error">'+esc(e.message)+'</p>';}
}
$('users-nav').onclick=openUsers;

